- name: Update apt cache
  become: true
  apt:
    cache_valid_time: "{{ cache_valid_time }}"
    update_cache: true

- name: Upgrade all packages
  become: true
  apt:
    upgrade: dist

- include: reboot.yml
  tags:
    - reboot
