- name: Check packer version
  changed_when: (packer_version.rc != 0) or
                (packer_expected not in packer_version.stdout)
  failed_when: false
  register: packer_version
  command: packer -v

- name: Install packer
  become: true
  when: packer_version is changed
  unarchive:
    dest: /usr/bin
    mode: "755"
    remote_src: true
    src: "https://releases.hashicorp.com/packer/{{ packer_expected }}/packer_{{ packer_expected }}_{{ packer_binary }}.zip"
