- name: Check pipx existence
  changed_when: "no_pipx.rc != 0"
  failed_when: false
  register: no_pipx
  command: "{{ ansible_env.HOME }}/.local/bin/pipx --version"

- name: Install pipx
  when: no_pipx is changed
  command: "{{ ansible_env.HOME }}/.pyenv/shims/python -m pip install --user pipx"

- name: Add pipx config tho the .bashrc
  blockinfile:
    block: |
      export PATH=$HOME/.local/bin:$PATH
    marker: "# {mark} pipx ANSIBLE MANAGED BLOCK"
    path: "{{ ansible_env.HOME }}/.bashrc"
