- name: Check poetry existence
  changed_when: "version.rc != 0"
  failed_when: False
  register: current_poetry_version
  command: "{{ ansible_env.HOME }}/.poetry/bin/poetry -V"

- name: Install poetry
  when: current_poetry_version is changed
  shell: >
    set -o pipefail &&
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py |
    {{ ansible_env.HOME }}/.pyenv/shims/python
  args:
    executable: /bin/bash

- name: Update poetry
  changed_when: "'You are using the latest version' not in poetry_update.stdout"
  register: poetry_update
  shell: "{{ ansible_env.HOME }}/.poetry/bin/poetry self update"

- name: Add poetry config to the .bashrc
  blockinfile:
    block: |
      export PATH="$HOME/.poetry/bin:$PATH"
    insertbefore: BOF
    marker: "# {mark} poetry ANSIBLE MANAGED BLOCK"
    path: "{{ ansible_env.HOME }}/.bashrc"
