- name: Install packages for build Python
  become: true
  apt:
    cache_valid_time: "{{ cache_valid_time }}"
    name:
      - build-essential
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - llvm
      - python-openssl
      - tk-dev
      - xz-utils
      - zlib1g-dev
    update_cache: yes

- name: Clone/update pyenv
  git:
    dest: "{{ ansible_env.HOME }}/.pyenv"
    repo: https://github.com/pyenv/pyenv.git

- name: Check global Python version
  changed_when: "current_python.rc != 0 or python_version not in current_python.stdout"
  register: current_python
  command: "{{ ansible_env.HOME }}/.pyenv/shims/python -V"

- name: Install/modify default python for user
  args:
    executable: /bin/bash
  when: current_python is changed
  shell: >
    PYENV_ROOT="$HOME/.pyenv" &&
    PATH="$PYENV_ROOT/bin:$PATH" &&
    eval "$(pyenv init -)" &&
    pyenv install {{ python_version }} &&
    pyenv global {{ python_version }}

- name: Add pyenv config to the .bashrc
  blockinfile:
    insertbefore: BOF
    marker: "# {mark} pyenv ANSIBLE MANAGED BLOCK"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
      fi
    path: "{{ ansible_env.HOME }}/.bashrc"

- name: Change byobu python
  blockinfile:
    marker: "# {mark} byobu python ANSIBLE MANAGED BLOCK"
    block: |
      export BYOBU_PYTHON="$PYENV_ROOT/shims/python"
    path: ~/.bashrc
