- name: Check if reboot is required
  register: reboot_required
  stat:
    get_md5: no
    path: /var/run/reboot-required

- name: Reboot system if required
  become: true
  when: reboot_required.stat.exists
  reboot:
    msg: Rebooting to complete system upgrade
    reboot_timeout: 120
