- name: Check terraform-docs version
  changed_when: (terraform_docs_version.rc != 0) or
                (terraform_docs_expected not in terraform_docs_version.stdout)
  failed_when: false
  register: terraform_docs_version
  command: terraform-docs -v

- name: Install terraform-docs
  become: true
  when: terraform_docs_version is changed
  get_url:
    dest: /usr/bin/terraform-docs
    mode: "755"
    url: "https://github.com/terraform-docs/terraform-docs/releases/download/\
v{{ terraform_docs_expected }}/terraform-docs-v{{ terraform_docs_expected }}-{{ terraform_docs_binary }}"
