- name: Add terraform apt-key
  become: true
  register: terraform_key_added
  apt_key:
    state: present
    url: https://apt.releases.hashicorp.com/gpg

- name: Add terraform apt repository
  become: true
  register: terraform_repo_added
  when: terraform_key_added is changed
  apt_repository:
    mode: "666"
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Run the equivalent of "apt-get update"
  when: terraform_key_added is changed
  apt:
    update_cache: true

- name: Install terraform
  become: true
  apt:
    name: terraform={{ terraform_expected }}
    # allow_downgrades: yes
    force: true  # https://github.com/ansible/ansible/issues/29451
