- name: Check tflint version
  changed_when: (tflint_version.rc != 0) or
                (tflint_expected not in tflint_version.stdout)
  failed_when: false
  register: tflint_version
  command: "tflint -v"

- name: Install tflint
  become: true
  when: tflint_version is changed
  unarchive:
    dest: /usr/bin
    mode: "755"
    remote_src: true
    src: "https://github.com/terraform-linters/tflint/releases/download/v{{ tflint_expected }}/tflint_{{ tflint_binary }}.zip"
